import type { Metadata } from "next";

// Styled
import styled from "styled-components";
import StyledComponentsRegistry from "./registry";

const StyledLayout = styled.body``;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledLayout>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </StyledLayout>
    </html>
  );
}
